# Generated by Django 5.0.6 on 2024-06-08 06:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cloth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("category", models.CharField(max_length=50)),
                ("size", models.CharField(max_length=10)),
                ("color", models.CharField(max_length=30)),
                ("price", models.DecimalField(decimal_places=3, max_digits=10)),
                ("stock", models.IntegerField()),
            ],
        ),
    ]
