# Generated by Django 5.0.6 on 2024-06-08 06:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cloth_inv", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cloth",
            name="size",
            field=models.CharField(
                choices=[
                    ("s", "S"),
                    ("m", "M"),
                    ("l", "L"),
                    ("xl", "XL"),
                    ("xxl", "XXL"),
                ],
                default="l",
                max_length=10,
            ),
        ),
    ]
