# Generated by Django 5.0.6 on 2024-06-08 06:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cloth_inv", "0002_alter_cloth_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cloth",
            name="size",
            field=models.CharField(
                choices=[
                    ("S", "S"),
                    ("M", "M"),
                    ("L", "L"),
                    ("XL", "XL"),
                    ("XXL", "XXL"),
                ],
                default="L",
                max_length=10,
            ),
        ),
    ]
