# Generated by Django 5.0.6 on 2024-06-08 06:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cloth_inv", "0003_alter_cloth_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cloth",
            name="category",
            field=models.CharField(
                choices=[
                    ("SH", "Shirt"),
                    ("PT", "Pant"),
                    ("TS", "T-Shirt"),
                    ("ST", "Suit"),
                    ("IW", "Innerwear"),
                ],
                max_length=2,
            ),
        ),
    ]
