# Generated by Django 5.0.6 on 2024-06-08 06:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cloth_inv", "0005_alter_cloth_category_alter_cloth_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="cloth",
            name="created",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cloth",
            name="updated",
            field=models.DateField(auto_now=True),
        ),
    ]
